version: 1.0.{build}
skip_tags: true
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  COVERALLS_REPO_TOKEN:
    secure: H/XqHS0CYGBJhApZckgeBADFusKQbIPxztDt2K2GI6XxbiijgDuc0u17kUh3SV/F
before_build:
  - nuget restore ".\src\GameOfLife.sln"
build:
  project: .\src\GameOfLife.sln
  verbosity: minimal
test_script:
- ps: >-
    vstest.console.exe /inIsolation /Enablecodecoverage /TestAdapterPath:".\src\packages\xunit.runner.visualstudio.2.0.0-rc1-build1030\build\_common\" .\src\GameOfLife.xUnit.Tests\bin\Release\GameOfLife.xUnit.Tests.dll /Settings:CodeCoverage.runsettings

    $coverageFilePath = Resolve-Path -path "TestResults\*\*.coverage"
    
    $coverageFilePath = $coverageFilePath.ToString()
    
    if(Test-Path .\coverage.coveragexml){ rm .\coverage.coveragexml }

    ."VSCodeCoverageToXml.exe" -i "$coverageFilePath" -o coverage.xml 

    Push-AppveyorArtifact coverage.xml

    $coveralls = (Resolve-Path "src/packages/coveralls.net.*/csmacnz.coveralls.exe").ToString()

    & $coveralls --vscodecoverage -i coverage.coveragexml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID --useRelativePaths -o cov.json

    Push-AppveyorArtifact cov.json
